import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { randomUUID } from 'node:crypto';

const raw = process.env.YT_DLP_COOKIES_CONTENT || '';
const suppliedPath = process.env.YT_DLP_COOKIES_FILE || '';

export function validateCookies(text) {
  if (typeof text !== 'string' || !text.trim()) return { valid: false, reason: 'empty' };
  const rows = text.replace(/^\uFEFF/, '').split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter((line) => line.trim() && !line.startsWith('# Netscape HTTP Cookie File') && !line.startsWith('# HTTP Cookie File') && !line.startsWith('# Generated by'));
  if (!rows.length) return { valid: false, reason: 'no_cookie_rows' };
  const validRow = (row) => {
    const fields = row.startsWith('#HttpOnly_') ? row.slice(10).split('\t') : row.split('\t');
    return fields.length === 7 && fields[0].length > 0 && /^(TRUE|FALSE)$/i.test(fields[1]) &&
      fields[2].startsWith('/') && /^(TRUE|FALSE)$/i.test(fields[3]) && /^\d+$/.test(fields[4]) &&
      fields[5].length > 0;
  };
  return rows.every(validRow) ? { valid: true } : { valid: false, reason: 'invalid_netscape_format' };
}

export let cookieStatus = { configured: false, valid: false, source: 'none', reason: null };
export let runtimeCookiePath = '';
if (raw) {
  const checked = validateCookies(raw);
  cookieStatus = { configured: true, valid: checked.valid, source: 'environment', reason: checked.reason };
  if (checked.valid) {
    runtimeCookiePath = path.join(os.tmpdir(), `relay-ytdlp-cookies-${randomUUID()}.txt`);
    fs.writeFileSync(runtimeCookiePath, raw, { flag: 'wx', mode: 0o600 });
    try { fs.chmodSync(runtimeCookiePath, 0o600); } catch {}
    process.env.YT_DLP_COOKIES_FILE = runtimeCookiePath;
  }
} else if (suppliedPath) {
  try {
    const checked = validateCookies(fs.readFileSync(suppliedPath, 'utf8'));
    cookieStatus = { configured: true, valid: checked.valid, source: 'file', reason: checked.reason };
  } catch {
    cookieStatus = { configured: true, valid: false, source: 'file', reason: 'file_unreadable' };
  }
}
